name: zxing2
description: A multi-format 1D/2D barcode image processing library implemented in Dart. This is a port of the Android library.
version: 0.1.0
homepage: https://github.com/xvrh/zxing-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  charcode: ^1.2.0
  collection: ^1.15.0
  fixnum: ^1.0.0
  meta: ^1.3.0

dev_dependencies:
  analyzer:
  dart_style:
  image:
  path:
  pub_semver:
  test:
  yaml: